# Generated by Django 5.1 on 2024-08-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('lugar', models.CharField(max_length=100)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
