# Generated by Django 5.1 on 2024-08-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_recordatorio_delete_recordatorio1'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorreoEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254)),
                ('archivo', models.FileField(upload_to='archivos/')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('visto', models.BooleanField(default=False)),
                ('descargado', models.BooleanField(default=False)),
            ],
        ),
    ]
