# Generated by Django 5.1 on 2024-08-27 22:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_correoenviado'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorreoEnviado1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254)),
                ('archivo', models.FileField(upload_to='archivos/')),
                ('abierto', models.BooleanField(default=False)),
                ('descargado', models.BooleanField(default=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('enviado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CorreoEnviado',
        ),
    ]
