# Generated by Django 5.1 on 2024-08-27 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_correoenviado1_delete_correoenviado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correoenviado1',
            name='enviado_en',
        ),
    ]
